services:
    Symfony\Component\DependencyInjection\ContainerInterface: '@service_container'
    Siestacat\DoctrineOdmEventListener\EventListener:
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: preRemove }
            -  { name: doctrine_mongodb.odm.event_listener, event: postRemove }
            -  { name: doctrine_mongodb.odm.event_listener, event: prePersist }
            -  { name: doctrine_mongodb.odm.event_listener, event: postPersist }
            -  { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
            -  { name: doctrine_mongodb.odm.event_listener, event: postUpdate }
            -  { name: doctrine_mongodb.odm.event_listener, event: preLoad }
            -  { name: doctrine_mongodb.odm.event_listener, event: postLoad }
        arguments:
            $container: '@service_container'